# FakeRank
Hrishi Dharam, Eilam Levitov  
March 16, 2017  

### Abstract 


In [1]:
import numpy as np
import util # Linear Algebra/PageRank
import misc # Random libraries and graphing
import matplotlib.pyplot as plt
import ipywidgets as widgets
%matplotlib inline  

In [2]:
# 1) Google Search
inputText = widgets.Text()
inputText

In [3]:
inputText.value.decode('unicode_escape').encode('ascii','ignore')

'lol rolf'

In [4]:
links = misc.gSearch(str(inputText.value.decode('unicode_escape').encode('ascii','ignore')))

Retrieving pages...
https://www.allaboutcounseling.com/forum/general-support/what-do-lol-and-rolf-stand-for/
https://tvaraj.com/2014/04/14/what-does-lol-lmao-rofl-brb-afk-ty-thx-etc-mean/
http://www.internetslang.com/ROLF-meaning-definition.asp
http://www.memecenter.com/search/rolf
http://www.memecenter.com/fun/119845/What-you-wrote-LOL-ROLF-LMFAO
http://www.quickmeme.com/meme/35h2gd
http://rofl.motifake.com/tags/rofl
http://www.funnyjunk.com/funny_pictures/3215135/Rolf/
http://www.riftherald.com/lol-gameplay/2016/11/16/13655258/replay-files-rofl-lol-client-update
http://boards.na.leagueoflegends.com/en/c/miscellaneous/nFFznEqK-how-do-i-open-rofl-replay-files
https://en.wikipedia.org/wiki/LOL
http://www.teamliquid.net/forum/general/9147-rolf-lmao-etc
http://www.urbandictionary.com/define.php?term=ROLF
http://www.taringa.net/posts/humor/5982143/Significado-De-lol-rolf-lmao-owned-fail-wtf.html
Pages retrieved
3.93485999107


In [5]:
print len(links)

14


In [6]:
# 2) Create Similarity Matrix
mtx = misc.simMatrix(links)

Generating similarity vectors...
Similarity Matrix computed
22.6561739445


In [7]:
print mtx
for i in mtx:
    if sum(i) == 0:
        print i
        print "isn't working"

[[ 0.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  0.  1.  1.  0.  0.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  0.  1.  0.  0.  0.  1.  1.  0.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  1.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.  0.  0.  1.  0.  0.  1.  1.  1.]
 [ 1.  1.  1.  0.  0.  0.  1.  0.  0.  0.  0.  1.  1.  0.]
 [ 1.  1.  1.  1.  1.  0.  1.  0.  0.  1.  1.  0.  1.  1.]
 [ 1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  0.  0.]
 [ 1.  1.  1.  1.  1.  0.  0.  1.  0.  1.  0.  1.  0.  0.]]
